project:
  type: website

website:
  title: "HD-MEA Tutorials for e-phac Users"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maxtwo_part1.qmd
        text: Part 1
      - href: maxtwo_part2.qmd
        text: Part 2
      - href: maxtwo_part3.qmd
        text: Part 3
      - href: maxtwo_part4.qmd
        text: Part 4
      - href: maxtwo_part5.qmd
        text: Part 5
      - href: about.qmd
        text: About Us
  sidebar:
    contents: auto
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

